# 应用名称
spring.application.name:  yms-cloud-web

# 发现服务配置
eureka.client.serviceUrl.defaultZone:
http://admin:Cloud_2016@10.2.61.201:9000/eureka/,
http://admin:Cloud_2016@10.2.61.202:9000/eureka/,
http://admin:Cloud_2016@10.2.61.203:9000/eureka/
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

# 远程连接timeout
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon.ConnectTimeout: 3000
ribbon.ReadTimeout: 60000

# 监控配置
endpoints.enabled: false
endpoints.logfile.enabled: true
endpoints.trace.enabled: true
endpoints.metrics.enabled: true
endpoints.health.enabled: true


## 日志配置
#logging.file: /tmp/logs/${spring.application.name}
#logging.level.root: INFO


## 旧的Premise配置
server:
    port: 80

# 用户中心服务
microservice.user.host:

# VCCloud服务
microservice.vccloud.host:



---
spring:
  profiles: dev

#eureka.client.serviceUrl.defaultZone: http://admin:Cloud_2016@127.0.0.1:9000/eureka/
eureka.client.serviceUrl.defaultZone:
http://admin:Cloud_2016@10.2.61.201:9000/eureka/,
http://admin:Cloud_2016@10.2.61.202:9000/eureka/,
http://admin:Cloud_2016@10.2.61.203:9000/eureka/
microservice.user.host:

---
spring:
  profiles: integration

eureka.client.serviceUrl.defaultZone:
http://admin:Cloud_2016@10.2.61.201:9000/eureka/,
http://admin:Cloud_2016@10.2.61.202:9000/eureka/,
http://admin:Cloud_2016@10.2.61.203:9000/eureka/
microservice.user.host:

---
spring:
  profiles: product

eureka.client.serviceUrl.defaultZone:
http://admin:Cloud_2016@139.196.97.209:9000/eureka/,
http://admin:Cloud_2016@106.14.8.230:9000/eureka/,
http://admin:Cloud_2016@139.196.121.163:9000/eureka/
microservice.user.host:
